/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import Beans.LoginBean;
import java.awt.Container;
import java.awt.Toolkit;

/**
 *
 * @author Abhishek Goyal
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private LoginBean objbean;
    static Container c;
    private String user_type;

    public MainFrame(LoginBean objbean) {
        this.objbean = objbean;
        this.user_type = objbean.getType();
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        c = this.getContentPane();
        if (this.user_type.equalsIgnoreCase("admin")) {

            mnuReports.remove(mnuEmployeeReport);
            mbMainFrame.remove(mnuProjects);
            mbMainFrame.remove(mnuMyJobs);
        }else if(this.user_type.equalsIgnoreCase("Employer")){
            mbMainFrame.remove(mnuManage);
            mbMainFrame.remove(mnuMyJobs);
            mbMainFrame.remove(mnuReports);
        }else if(this.user_type.equalsIgnoreCase("Employee")){
            mbMainFrame.remove(mnuTracker);
            mbMainFrame.remove(mnuReports);
            mbMainFrame.remove(mnuProjects);
            mbMainFrame.remove(mnuManage);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        lbImg1 = new javax.swing.JLabel();
        mbMainFrame = new javax.swing.JMenuBar();
        mnuProfile = new javax.swing.JMenu();
        mnuTracker = new javax.swing.JMenu();
        mnuManage = new javax.swing.JMenu();
        mnuEmployeeManage = new javax.swing.JMenuItem();
        mnuEmployerManage = new javax.swing.JMenuItem();
        mnuProjects = new javax.swing.JMenu();
        mnuCreateProject = new javax.swing.JMenuItem();
        mnuViewProjects = new javax.swing.JMenuItem();
        mnuAssignProject = new javax.swing.JMenuItem();
        mnuMyJobs = new javax.swing.JMenu();
        mnuReports = new javax.swing.JMenu();
        mnuEmployeeReport = new javax.swing.JMenuItem();
        mnuUserReport = new javax.swing.JMenuItem();
        mnuProjectReport = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu7.setText("jMenu7");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lbImg1);
        lbImg1.setBounds(10, 10, 820, 340);

        mnuProfile.setText("Profile ");
        mnuProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProfileMouseClicked(evt);
            }
        });
        mbMainFrame.add(mnuProfile);

        mnuTracker.setText("Tracker");
        mnuTracker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuTrackerMouseClicked(evt);
            }
        });
        mbMainFrame.add(mnuTracker);

        mnuManage.setText("Manage");

        mnuEmployeeManage.setText("Employee's");
        mnuEmployeeManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployeeManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuEmployeeManage);

        mnuEmployerManage.setText("Employer's");
        mnuEmployerManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployerManageActionPerformed(evt);
            }
        });
        mnuManage.add(mnuEmployerManage);

        mbMainFrame.add(mnuManage);

        mnuProjects.setText("Projects");

        mnuCreateProject.setText("Create New Project");
        mnuCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateProjectActionPerformed(evt);
            }
        });
        mnuProjects.add(mnuCreateProject);

        mnuViewProjects.setText("View Projects");
        mnuViewProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewProjectsActionPerformed(evt);
            }
        });
        mnuProjects.add(mnuViewProjects);

        mnuAssignProject.setText("Assign Project");
        mnuAssignProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAssignProjectActionPerformed(evt);
            }
        });
        mnuProjects.add(mnuAssignProject);

        mbMainFrame.add(mnuProjects);

        mnuMyJobs.setText("My Jobs");
        mnuMyJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMyJobsMouseClicked(evt);
            }
        });
        mnuMyJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMyJobsActionPerformed(evt);
            }
        });
        mbMainFrame.add(mnuMyJobs);

        mnuReports.setText(" Reports");
        mnuReports.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnuReports.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuReports.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuReportsMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnuReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuReportsMouseClicked(evt);
            }
        });
        mnuReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportsActionPerformed(evt);
            }
        });

        mnuEmployeeReport.setText("Employee Report");
        mnuEmployeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployeeReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuEmployeeReport);

        mnuUserReport.setText("User Report");
        mnuUserReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuUserReport);

        mnuProjectReport.setText("Project Report");
        mnuProjectReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProjectReportActionPerformed(evt);
            }
        });
        mnuReports.add(mnuProjectReport);

        mbMainFrame.add(mnuReports);

        jMenu8.setText("Logout");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        mbMainFrame.add(jMenu8);

        setJMenuBar(mbMainFrame);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProfileMouseClicked
        // TODO add your handling code here: 
        c.removeAll();
        c.setVisible(false);
        if (this.user_type.equalsIgnoreCase("admin")) {

            UserProfile up = new UserProfile(this.objbean);
            up.setBounds(10, 10, 900, 630);
            c.add(up);

        } else if (this.user_type.equalsIgnoreCase("Employee")) {
            EmployeeProfile ep = new EmployeeProfile(this.objbean);
            ep.setBounds(10, 10, 940, 790);
            c.add(ep);
        } else if (this.user_type.equalsIgnoreCase("Employer")) {
            EmployerProfile employer_Profile = new EmployerProfile(this.objbean);
            employer_Profile.setBounds(10, 10, 1020, 820);
            c.add(employer_Profile);
        }

        c.setVisible(true);
    }//GEN-LAST:event_mnuProfileMouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        LoginFrame sif = new LoginFrame();
        sif.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu8MouseClicked

    private void mnuEmployeeManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployeeManageActionPerformed
        // TODO add your handling code here:

        c.removeAll();
        c.setVisible(false);
        if (this.user_type.equalsIgnoreCase("admin")) {
            AdminManageEmployee ame = new AdminManageEmployee();
            ame.setBounds(10, 10, 1200, 740);
            c.add(ame);
        }
        c.setVisible(true);
    }//GEN-LAST:event_mnuEmployeeManageActionPerformed

    private void mnuReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuReportsActionPerformed

    private void mnuReportsMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuReportsMenuKeyPressed
        // TODO add your handling code here

    }//GEN-LAST:event_mnuReportsMenuKeyPressed

    private void mnuReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReportsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuReportsMouseClicked

    private void mnuMyJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMyJobsMouseClicked
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        EmployeeJobs ejobs = new EmployeeJobs(objbean);
        ejobs.setBounds(10, 10, 760, 710);
        c.add(ejobs);
        c.setVisible(true);
    }//GEN-LAST:event_mnuMyJobsMouseClicked

    private void mnuEmployerManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployerManageActionPerformed
        // TODO add your handling code here:
        c.removeAll();;
        c.setVisible(false);
        if (this.user_type.equalsIgnoreCase("admin")) {
            AdminManageUser amu = new AdminManageUser();
            amu.setBounds(10, 10, 1600, 800);
            c.add(amu);
        }
        c.setVisible(true);

    }//GEN-LAST:event_mnuEmployerManageActionPerformed

    private void mnuAssignProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAssignProjectActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        TaskAssigner ta = new TaskAssigner(this.objbean);
        ta.setBounds(10, 10, 1120, 856);
        c.add(ta);
        c.setVisible(true);

    }//GEN-LAST:event_mnuAssignProjectActionPerformed

    private void mnuCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateProjectActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        ProjectManager pm = new ProjectManager(this.objbean);
        pm.setBounds(10, 10, 1120, 800);
        c.add(pm);
        c.setVisible(true);
    }//GEN-LAST:event_mnuCreateProjectActionPerformed

    private void mnuMyJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMyJobsActionPerformed
        // TODO add your handling code here:
        /*c.removeAll();
        c.setVisible(false);
        EmployeeJobs ej = new EmployeeJobs(this.objbean);
        ej.setBounds(10, 10, 760, 710);
        c.add(ej);
        c.setVisible(true);*/
    }//GEN-LAST:event_mnuMyJobsActionPerformed

    private void mnuEmployeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployeeReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEmployeeReportActionPerformed

    private void mnuUserReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserReportActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        if (this.user_type.equalsIgnoreCase("admin")) {
            AdminUserReport ej = new AdminUserReport();
            ej.setBounds(10, 10, 1110, 820);
            c.add(ej);
        }
        c.setVisible(true);
    }//GEN-LAST:event_mnuUserReportActionPerformed

    private void mnuProjectReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProjectReportActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        if (this.user_type.equalsIgnoreCase("admin")) {
            AdminProjectReport ej = new AdminProjectReport();
            ej.setBounds(10, 10, 1132, 614);
            c.add(ej);
        }
        c.setVisible(true);
    }//GEN-LAST:event_mnuProjectReportActionPerformed

    private void mnuTrackerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTrackerMouseClicked
        // TODO add your handling code here:
        c.removeAll();;
        c.setVisible(false);
        Tracker amu = new Tracker(objbean);
        amu.setBounds(10, 10, 1371, 850);
        c.add(amu);
        c.setVisible(true);
    }//GEN-LAST:event_mnuTrackerMouseClicked

    private void mnuViewProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewProjectsActionPerformed
        // TODO add your handling code here:
        c.removeAll();;
        c.setVisible(false);
        if(this.user_type.equalsIgnoreCase("Employer")){
            EmployerProjectsList epl=new EmployerProjectsList(this.objbean);
            epl.setBounds(10, 10, 960, 550);
            c.add(epl);
        }else if(this.user_type.equalsIgnoreCase("Employee")){
            
        }
        c.setVisible(true);
    }//GEN-LAST:event_mnuViewProjectsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbImg1;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem mnuAssignProject;
    private javax.swing.JMenuItem mnuCreateProject;
    private javax.swing.JMenuItem mnuEmployeeManage;
    private javax.swing.JMenuItem mnuEmployeeReport;
    private javax.swing.JMenuItem mnuEmployerManage;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenu mnuMyJobs;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenuItem mnuProjectReport;
    private javax.swing.JMenu mnuProjects;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuTracker;
    private javax.swing.JMenuItem mnuUserReport;
    private javax.swing.JMenuItem mnuViewProjects;
    // End of variables declaration//GEN-END:variables
}
