/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import Beans.EmployeeBean;
import Beans.LoginBean;
import Beans.ProjectBean;
import Beans.TaskBean;
import Services.ManageEmployeeServices;
import Services.ManageEmployerServices;
import Services.ManageUser;
import Services.ProjectManagerServices;
import Services.TaskManager;
import Utility.Utilities;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author Abhishek Goyal
 */
public class TaskAssigner extends javax.swing.JPanel {

    /**
     * Creates new form TaskAssigner
     */
    private ArrayList<ProjectBean> pbal;
    /* private ArrayList<TaskBean> tbal;*/
    private ArrayList<EmployeeBean> ebal;
    private ArrayList<LoginBean> lbal;
    private int emp_id;
    private int project_id;
    private int no_of_employess_selected;
    private double budget_left;

    public TaskAssigner(LoginBean objbean) {

        initComponents();
        emp_id = ManageEmployerServices.getSingleEmployer(objbean.getLogin_id()).getEmp_id();
        System.out.println("552" + emp_id);
        pbal = ProjectManagerServices.getAllProjects(emp_id);
        ebal = ManageEmployeeServices.getAllEmployee();
        lbal = ManageUser.getAllUser("employee");
        showProjectNameInComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ddlProjectName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtEmployerId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmployeesRequired = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ddlRatings = new javax.swing.JComboBox<>();
        txtExperienceSort = new javax.swing.JTextField();
        txtSalarySort = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoofJobsDone = new javax.swing.JTextField();
        btnList = new javax.swing.JButton();
        btnListAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployeeList = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEmployeeId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRemainingBudget = new javax.swing.JTextField();
        txtNoofEmployeesSelected = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Project Name");

        ddlProjectName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlProjectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddlProjectNameMouseClicked(evt);
            }
        });
        ddlProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlProjectNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Employer Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Budget");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("No of Employees Required");

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddlProjectName, 0, 228, Short.MAX_VALUE)
                    .addComponent(txtEmployeesRequired))
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmployerId, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(txtBudget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnShow)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShow))
                        .addGap(43, 83, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddlProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeesRequired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(88, 30));

        jLabel12.setText("Task Assigner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sorting Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Experience");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Salary");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Rating");

        ddlRatings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "1 Star", "2 Star", "3 Star", "4Star", "5 Star" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("No of Jobs Done");

        btnList.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnListAll.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnListAll.setText("List All");
        btnListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoofJobsDone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperienceSort, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSalarySort)
                    .addComponent(ddlRatings, 0, 178, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtExperienceSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarySort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnList))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNoofJobsDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ddlRatings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAll))
                .addGap(20, 20, 20))
        );

        tableEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Contact", "Email", "Gender", "No of Jobs Done", "Salary", "Ratings", "Experience"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmployeeList);
        if (tableEmployeeList.getColumnModel().getColumnCount() > 0) {
            tableEmployeeList.getColumnModel().getColumn(0).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(1).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(2).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(3).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(4).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(5).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(6).setResizable(false);
            tableEmployeeList.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Enter Employee Id");

        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        txtEmployeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmployeeIdKeyPressed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("No of Employees Selected");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Remaining Budget");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmployeeId)
                    .addComponent(txtNoofEmployeesSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel11)
                        .addGap(41, 41, 41)
                        .addComponent(txtRemainingBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemainingBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoofEmployeesSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void showProjectNameInComboBox() {
        ddlProjectName.removeAllItems();
        ddlProjectName.addItem("No");
        for (int i = 0; i < pbal.size(); i++) {
            ProjectBean projectbean = pbal.get(i);
            if (projectbean.getEmp_id() == emp_id) {

                ddlProjectName.addItem(projectbean.getProject_name());
            }

        }
    }
    private void ddlProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlProjectNameActionPerformed
        // TODO add your handling code here:
        //showProjectDetails();

    }//GEN-LAST:event_ddlProjectNameActionPerformed

    private void txtEmployeeIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entryIntoTable();

        }
    }//GEN-LAST:event_txtEmployeeIdKeyPressed
    private void entryIntoTable() {
        if (txtEmployeeId.getText().isEmpty()) {
            Utilities.showMsg(this, "Please Enter user Id", 2);
            txtEmployeeId.requestFocus();
        } else {
            double salary = 0.0;
            boolean flag = false;
            for (int i = 0; i < ebal.size(); i++) {
                if (ebal.get(i).getEmployee_id() == Integer.parseInt(txtEmployeeId.getText())) {
                    flag = true;
                    salary = ebal.get(i).getHourly_salary() * 12 * 30;
                }
            }
            if (flag) {
                TaskBean objbean = new TaskBean();
                objbean.setEmployee_id((Integer.parseInt(txtEmployeeId.getText())));
                objbean.setEmp_id(emp_id);
                objbean.setProject_id(project_id);
                objbean.setStatus(true);
                if (TaskManager.addTask(objbean)) {
                    Utilities.showMsg(this, "Task Assigned Succesfully", 0);
                    txtNoofEmployeesSelected.setText(String.valueOf(--no_of_employess_selected));
                    txtRemainingBudget.setText(String.valueOf(budget_left - salary));

                } else {
                    Utilities.showMsg(this, "Task Already Assigned", 1);
                }
            } else {
                Utilities.showMsg(this, "Enter Correct Employee Id", 1);
            }
        }
    }
    private void ddlProjectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddlProjectNameMouseClicked
        // TODO add your handling code here:
        // showProjectDetails();
        //showTableEnteries();
    }//GEN-LAST:event_ddlProjectNameMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (btnAdd.isSelected()) {
            entryIntoTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:

        int experience = -1, no_of_jobs_done = -1, ratings = -1;
        double salary = -1;
        if (txtExperienceSort.getText().trim().isEmpty()) {
            if (txtSalarySort.getText().trim().isEmpty()) {
                if (ddlRatings.getSelectedIndex() == 0) {

                    if (txtNoofEmployeesSelected.getText().trim().isEmpty()) {
                        Utilities.showMsg(this, "Please Entery on of fields", 2);
                    }
                }
            }
        } else {

            
            if (ddlRatings.getSelectedIndex() > 0) {
                ratings = ddlRatings.getSelectedIndex();

            }

            if (txtExperienceSort.getText().trim().isEmpty()) {
                experience = -1;
            } else {
                experience = Integer.parseInt(txtExperienceSort.getText().trim());
            }

            if (txtSalarySort.getText().trim().isEmpty()) {
                salary = -1;
            } else {
                salary = Double.parseDouble(txtSalarySort.getText().trim());
            }

            
            if (txtNoofEmployeesSelected.getText().trim().isEmpty()) {
                no_of_jobs_done = -1;
            } else {
                no_of_jobs_done = Integer.parseInt(txtNoofEmployeesSelected.getText().trim());

            }

        }
        ebal = ManageEmployeeServices.getSearchEmployee(experience, salary, no_of_jobs_done, ratings);
        showTableEnteries();
    }//GEN-LAST:event_btnListActionPerformed

    private void btnListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllActionPerformed
        // TODO add your handling code here:
        ebal = ManageEmployeeServices.getAllEmployee();
        showTableEnteries();
    }//GEN-LAST:event_btnListAllActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        showProjectDetails();
        showTableEnteries();
    }//GEN-LAST:event_btnShowActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed
    public void showProjectDetails() {

        ProjectBean objbean = ProjectManagerServices.getSingleProject((String) ddlProjectName.getSelectedItem());

        txtEmployeesRequired.setText(String.valueOf(objbean.getEmp_requirement()));
        txtEmployerId.setText(String.valueOf(emp_id));
        txtBudget.setText(String.valueOf(objbean.getBudget_project()));
        project_id = objbean.getProject_id();
        no_of_employess_selected = objbean.getEmp_requirement();
        budget_left = objbean.getBudget_project();

    }

    public void showTableEnteries() {
        enableTextFields();
        enableButtons(true);
        String heading[] = {"EmployeeID", "Name", "Contact", "Email", "Gender", "No of Jobs Done", "Salary", "Ratings", "Experience"};
        String data[][] = new String[ebal.size()][heading.length];
        for (int i = 0; i < ebal.size(); i++) {
            EmployeeBean objbean = ebal.get(i);
            LoginBean loginbean = ManageUser.getSingleLoginBean(objbean.getLogin_id());
            data[i][0] = String.valueOf(objbean.getEmployee_id());
            data[i][1] = loginbean.getName();
            data[i][2] = String.valueOf(loginbean.getContact());
            data[i][3] = loginbean.getEmail();
            if (loginbean.isGender()) {
                data[i][4] = "Male";
            } else {
                data[i][4] = "Female";
            }
            data[i][5] = String.valueOf(objbean.getNo_of_jobs_done());
            data[i][6] = String.valueOf(objbean.getHourly_salary());
            data[i][7] = String.valueOf(objbean.getRatings());
            data[i][8] = String.valueOf(objbean.getExperience());

        }
        tableEmployeeList = new JTable(data, heading);
        jScrollPane1.setViewportView(tableEmployeeList);

    }

    public void enableTextFields() {
        boolean flag = true;
        ddlProjectName.setEnabled(flag);
        txtEmployeeId.setEditable(flag);
        txtEmployeesRequired.setEditable(flag);
        txtBudget.setEditable(flag);
        txtExperienceSort.setEditable(flag);
        txtSalarySort.setEditable(flag);
        txtNoofJobsDone.setEditable(flag);
        ddlRatings.setEnabled(flag);
        txtEmployerId.setEditable(flag);
        txtNoofEmployeesSelected.setEditable(false);
        txtRemainingBudget.setEditable(false);
    }

    public void enableButtons(boolean flag) {
        btnList.setEnabled(flag);
        btnListAll.setEnabled(flag);
        btnAdd.setEnabled(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnListAll;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> ddlProjectName;
    private javax.swing.JComboBox<String> ddlRatings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmployeeList;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeesRequired;
    private javax.swing.JTextField txtEmployerId;
    private javax.swing.JTextField txtExperienceSort;
    private javax.swing.JTextField txtNoofEmployeesSelected;
    private javax.swing.JTextField txtNoofJobsDone;
    private javax.swing.JTextField txtRemainingBudget;
    private javax.swing.JTextField txtSalarySort;
    // End of variables declaration//GEN-END:variables
}
